project:
  type: website
  output-dir: public

website:
  title: "Portfolio"
  site-url: "https://mirramockakid.github.io/Portfolio/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: auto
